from .Circle import Circle
from .HistologyImage import HistologyImage
from .EquilateralTriangle import EquilateralTriangle
from .Gradient import Gradient
from .Line import Line
from .Oval import Oval
from .Rectangle import Rectangle
from .SineWave import SineWave
from .Square import Square
from .Texture import Texture
from .Triangle import Triangle